# Generated by Django 4.0 on 2021-12-28 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_toy'),
    ]

    operations = [
        migrations.AddField(
            model_name='snake',
            name='toys',
            field=models.ManyToManyField(to='main_app.Toy'),
        ),
    ]
